# Generated by Django 3.1.2 on 2020-11-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
                ('nid_or_pass', models.CharField(max_length=150)),
                ('license_plate_number', models.CharField(max_length=150)),
                ('license', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('company_details', models.TextField()),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.serviceman')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_pickup_time', models.TimeField()),
                ('delivery_receive_time', models.TimeField()),
                ('is_active', models.BooleanField()),
                ('delivery_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryservice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.serviceman')),
            ],
        ),
    ]
